-- SECTION D : PRICING AND RATINGS
;

-- 01 IF A MEAT LOVERS PIZZA COSTS $12 AND VEGETARIAN COSTS $10 AND THERE WERE NO CHARGES FOR CHANGES 
-- HOW MUCH MONEY HAS PIZZA RUNNER MADE SO FAR IF THERE ARE NO DELIVERY FEES?
;

-- 02 WHAT IF THERE WAS AN ADDITIONAL $1 CHARGE FOR ANY PIZZA EXTRAS?
-- ADD CHEESE IS $1 EXTRA
;

-- 03 THE PIZZA RUNNER TEAM NOW WANTS TO ADD AN ADDITIONAL RATINGS SYSTEM THAT ALLOWS CUSTOMERS TO RATE THEIR RUNNER, 
-- HOW WOULD YOU DESIGN AN ADDITIONAL TABLE FOR THIS NEW DATASET 
-- GENERATE A SCHEMA FOR THIS NEW TABLE AND INSERT YOUR OWN DATA FOR RATINGS FOR EACH SUCCESSFUL CUSTOMER ORDER BETWEEN 1 TO 5.
;

-- 04 USING YOUR NEWLY GENERATED TABLE 
-- CAN YOU JOIN ALL OF THE INFORMATION TOGETHER TO FORM A TABLE WHICH HAS THE FOLLOWING INFORMATION FOR SUCCESSFUL DELIVERIES?
-- - CUSTOMER_ID
-- - ORDER_ID
-- - RUNNER_ID
-- - RATING
-- - ORDER_TIME
-- - PICKUP_TIME
-- - TIME BETWEEN ORDER AND PICKUP
-- - DELIVERY DURATION
-- - AVERAGE SPEED
-- - TOTAL NUMBER OF PIZZAS
;

-- Assuming you have 10 rows in RUNNER_ORDERS and want to set DELIVERY_TIME for each.
;

-- Adjust the data type and values as needed
;

-- 05 IF A MEAT LOVERS PIZZA WAS $12 AND VEGETARIAN $10 FIXED PRICES WITH NO COST FOR EXTRAS AND EACH RUNNER IS PAID $0.30 PER KILOMETER TRAVELED
-- HOW MUCH MONEY DOES PIZZA RUNNER HAVE LEFT OVER AFTER THESE DELIVERIES?